export const enum HubSaleInquiryErrorCode {
  /**
   * The question post is not mine.
   */
  OWNERSHIP = "HUB_SALE_INQUIRY_OWNERSHIP",

  INQUIRY_NOT_FOUND = "HUB_SALE_INQUIRY_NOT_FOUND",

  QUESTION_NOT_FOUND = "HUB_SALE_INQUIRY_QUESTION_NOT_FOUND",

  LIKE_NOT_FOUND = "HUB_SALE_INQUIRY_LIKE_NOT_FOUND",

  COMMENT_NOT_FOUND = "HUB_SALE_INQUIRY_COMMENT_NOT_FOUND",
}
