export const enum CommonErrorCode {
  // PRISMA ERRORS`
  RECORD_NOT_FOUND = "RECORD_NOT_FOUND",
  UNIQUE_CONSTRAINT_VIOLATED = "UNIQUE_CONSTRAINT_VIOLATED",
  INTERNAL_PRISMA_ERROR = "INTERNAL_PRISMA_ERROR",
  //--------------------

  // COMMON ERRORS
  INVALID_TABLE = "INVALID_TABLE",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  S3_INTERNAL_ERROR = "S3_INTERNAL_ERROR",
  CDS_INTERNAL_ERROR = "CDS_INTERNAL_ERROR",
  INVALID_S3_URL = "INVALID_S3_URL",
  EXTERNAL_SWAGGER_URL_ERROR = "EXTERNAL_SWAGGER_URL_ERROR",
  INVALID_JWT = "INVALID_JWT",
  GOOGLE_API_ERROR = "GOOGLE_API_ERROR",
  APPLE_API_ERROR = "APPLE_API_ERROR",
  NAVER_API_ERROR = "NAVER_API_ERROR",
  KAKAO_API_ERROR = "KAKAO_API_ERROR",
  CONNECTOR_SYNC_PASSWORD_ERROR = "CONNECTOR_SYNC_PASSWORD_ERROR",
  //--------------------
}
